/**
 * Lazy SQLite connection for the API.
 *
 * The connection is opened on **first query**, never on import: `createApp()`
 * must stay side-effect free (see `apps/api/src/app.ts` and the existing
 * `server.test.ts`), and tests must be able to import the app without touching
 * the user's database.
 */
import { Database as SqliteDatabase } from 'bun:sqlite';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { drizzle, type BunSQLiteDatabase } from 'drizzle-orm/bun-sqlite';
import { migrate } from 'drizzle-orm/bun-sqlite/migrator';
import { config, ensureDir, loggerFor } from '@webpilot/shared';
import * as schema from './schema';

const log = loggerFor('api:db');

export type Database = BunSQLiteDatabase<typeof schema>;

/** `apps/api/drizzle` — migrations generated by `bun run db:generate`. */
export const MIGRATIONS_DIR = fileURLToPath(new URL('../../drizzle', import.meta.url));

interface Handle {
  db: Database;
  sqlite: SqliteDatabase;
}

let handle: Handle | null = null;

/** Opens (and migrates) the local database. Idempotent. */
export function getDb(): Database {
  if (handle) return handle.db;

  ensureDir(path.dirname(config.dbUrl));
  const sqlite = new SqliteDatabase(config.dbUrl, { create: true });
  // WAL keeps concurrent readers (the dashboard) from blocking the agent's writes.
  sqlite.exec('PRAGMA journal_mode = WAL;');
  sqlite.exec('PRAGMA foreign_keys = ON;');

  const db = drizzle(sqlite, { schema });

  if (existsSync(MIGRATIONS_DIR)) {
    migrate(db, { migrationsFolder: MIGRATIONS_DIR });
  } else {
    log.warn('no migrations found — run `bun run db:generate`', { dir: MIGRATIONS_DIR });
  }

  handle = { db, sqlite };
  log.info('sqlite ready', { file: path.basename(config.dbUrl) });
  return db;
}

/** Closes the connection (shutdown / tests). */
export function closeDb(): void {
  if (!handle) return;
  handle.sqlite.close();
  handle = null;
}

/** Test helper: forget the cached handle without closing a foreign connection. */
export function resetDbHandle(): void {
  handle = null;
}

export { schema };